export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_ERROR = 'GET_USER_ERROR';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const EDIT_USER_EMAIL = 'EDIT_USER_EMAIL';
export const EDIT_USER_LOGIN = 'EDIT_USER_LOGIN';

export const EDIT_USER_PASSWORD = 'EDIT_USER_PASSWORD';
export const EDIT_USER_PASSWORD_ERROR = 'EDIT_USER_PASSWORD_ERROR';
export const EDIT_USER_PASSWORD_SUCCESS = 'EDIT_USER_PASSWORD_SUCCESS';

export const SET_SUCCESS_FALSE = "SET_SUCCESS_FALSE";

export const EDIT_USER_BIRTHDAY = 'EDIT_USER_BIRTHDAY';

