export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_ERROR = 'GET_USER_ERROR';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const PUT_USER_EMAIL = 'SET_USER_EMAIL';
export const PUT_USER_LOGIN = 'SET_USER_LOGIN';
export const PUT_USER_PASSWORD = 'SET_USER_PASSWORD';
export const PUT_USER_BIRTHDAY = 'SET_USER_BIRTHDAY';

